// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHK3Pcw17k2TUQJDYSI68k4dzFN7TjfFg',
    appId: '1:974253545168:web:056e0efe4399a0130130d5',
    messagingSenderId: '974253545168',
    projectId: 'questcompanion-4edfa',
    authDomain: 'questcompanion-4edfa.firebaseapp.com',
    storageBucket: 'questcompanion-4edfa.appspot.com',
    measurementId: 'G-XWSR813RCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRb9AaXFp873UKJIxWUsFN99vh7DETlTA',
    appId: '1:974253545168:android:4203aee3d5ee5d430130d5',
    messagingSenderId: '974253545168',
    projectId: 'questcompanion-4edfa',
    storageBucket: 'questcompanion-4edfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9qoIGmDEdp2aEvuTEVTc1pnjZDdmFes',
    appId: '1:974253545168:ios:14fbec57517e739c0130d5',
    messagingSenderId: '974253545168',
    projectId: 'questcompanion-4edfa',
    storageBucket: 'questcompanion-4edfa.appspot.com',
    iosClientId: '974253545168-lje8hq069hab0mo1j7a4nheu7tjrhvbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.questCompanion',
  );
}
